/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Sales;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kp
 */
public class POS extends javax.swing.JFrame {

    /**
     * Creates new form POS
     */
    java.util.Date date;
    java.sql.Date sqldate;
    
    DefaultTableModel model;
    int LineNum;
    int InvoiceNum;
    int ProdID;
    String ProdName;
    int Qty;
    int QtySold = 0;
    double Price;
    double Subtotal;
    double TotRevenue = 0;
    //Line number for invoice
    int lineCounter = 0;
    
    public POS() {
        initComponents();
        //showTables();
    }
    //New Sales object
    public POS(int InvoiceNum, int LineNum, int ProdID, int Qty, double Subtotal)
    {
        initComponents();
        //showTables();
        this.LineNum=LineNum;
        this.InvoiceNum = InvoiceNum;
        this.ProdID = ProdID;
        this.Qty = Qty;
        this.Subtotal = Subtotal;
    }
    //New sales object 
    public POS(int InvoiceNum, String Date, int Qty, double TotRevenue)
    {
        initComponents();
        //showTables();
        
        this.InvoiceNum = InvoiceNum;
        this.Qty=Qty;
        this.TotRevenue = TotRevenue;
    }
    public Products getProduct(){
        //product search starts at null
        Products productFind = null;
        //Create new data access object (DAO) to access Find functions in POSDAO
        POSDAO posDAO1 = new POSDAO();
        try {
            //Connect to database
            if(posDAO1.openConnection())
            {
                //accesses find function in POSDAO and assigns it to the search result
                productFind = posDAO1.findProductRecord(Integer.valueOf(txtPcode.getText()));

                if(productFind==null){
                //Alert that this is not a valid product code
                    JOptionPane.showMessageDialog(jPanel1,"This is not a valid Product ID. Please try again.");
                    txtPcode.setText("");
                    return null;
                }
            }
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(POS.class.getName()).log(Level.SEVERE, null, ex);
        }
        return productFind;
    }
    
    //Other getters for variables
    java.util.Date getJavaDate(){return date;}
    java.sql.Date getSQLDate(){return sqldate;}
    public int getLineNum(){return LineNum;}
    public int getInvoiceNum(){return InvoiceNum;}
    public int getProdID(){
        return getProduct().getProdID();
    }
    public String getProdName(){
        return getProduct().getProdName();
    }
    public int getQuantity(){
        Qty = (Integer)quantity.getValue();
        return Qty;
    }
    public int getQuantitySold(){return QtySold;}
    public double getPrice()
    {
        return getProduct().getUnitPrice();
    }
    public double getSubtotal(){
        Subtotal = getQuantity()*getPrice();
        return Subtotal;
    }
    public double getTotRevenue(){
        return TotRevenue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblPcode = new javax.swing.JLabel();
        lblPname = new javax.swing.JLabel();
        lblQty = new javax.swing.JLabel();
        lblSubtotal = new javax.swing.JLabel();
        lblPrice = new javax.swing.JLabel();
        txtPcode = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        txtPname = new javax.swing.JTextField();
        txtSubtotal = new javax.swing.JTextField();
        quantity = new javax.swing.JSpinner();
        addLineBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txtTotal = new javax.swing.JTextField();
        lblTotal = new javax.swing.JLabel();
        lblPay = new javax.swing.JLabel();
        lblBalance = new javax.swing.JLabel();
        txtPay = new javax.swing.JTextField();
        txtBalance = new javax.swing.JTextField();
        printBill = new javax.swing.JButton();
        paymentcombo = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtBill = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        saleshomebttn = new javax.swing.JButton();
        checkoutBtn = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        salesList = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "New Sale", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        lblPcode.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblPcode.setForeground(new java.awt.Color(255, 255, 255));
        lblPcode.setText("Product ID");

        lblPname.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblPname.setForeground(new java.awt.Color(255, 255, 255));
        lblPname.setText("Product Name");

        lblQty.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblQty.setForeground(new java.awt.Color(255, 255, 255));
        lblQty.setText("Quantity");

        lblSubtotal.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblSubtotal.setForeground(new java.awt.Color(255, 255, 255));
        lblSubtotal.setText("Sub Total");

        lblPrice.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblPrice.setForeground(new java.awt.Color(255, 255, 255));
        lblPrice.setText("Price");

        txtPcode.setBackground(new java.awt.Color(0, 0, 0));
        txtPcode.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtPcode.setForeground(new java.awt.Color(255, 255, 0));
        txtPcode.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPcodeFocusLost(evt);
            }
        });
        txtPcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPcodeActionPerformed(evt);
            }
        });
        txtPcode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPcodeKeyPressed(evt);
            }
        });

        txtPrice.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        txtPname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        txtSubtotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        quantity.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        quantity.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                quantityStateChanged(evt);
            }
        });

        addLineBtn.setText("Add Line");
        addLineBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addLineBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblPcode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtPcode, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(74, 74, 74)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPname)
                            .addComponent(txtPname, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblQty)
                            .addComponent(quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPrice)
                            .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(74, 74, 74)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSubtotal)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(addLineBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)))
                .addGap(48, 48, 48))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblPcode)
                        .addComponent(lblPname)
                        .addComponent(lblQty)
                        .addComponent(lblSubtotal))
                    .addComponent(lblPrice, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(addLineBtn)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        txtTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        lblTotal.setBackground(new java.awt.Color(255, 255, 255));
        lblTotal.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(255, 255, 255));
        lblTotal.setText("Total:");

        lblPay.setBackground(new java.awt.Color(255, 255, 255));
        lblPay.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblPay.setForeground(new java.awt.Color(255, 255, 255));
        lblPay.setText("Pay:");

        lblBalance.setBackground(new java.awt.Color(255, 255, 255));
        lblBalance.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblBalance.setForeground(new java.awt.Color(255, 255, 255));
        lblBalance.setText("Balance:");

        txtPay.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtPay.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPayFocusLost(evt);
            }
        });

        txtBalance.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        printBill.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        printBill.setText("PRINT BILL");
        printBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printBillActionPerformed(evt);
            }
        });

        paymentcombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--- Please Select Payment Type ---", "Cash", "Credit", "Debit", " " }));
        paymentcombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentcomboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(78, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(printBill)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(lblBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(paymentcombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(lblPay, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtPay, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(74, 74, 74))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotal)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPay, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtPay, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBalance)
                    .addComponent(txtBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(paymentcombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(printBill)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        txtBill.setColumns(20);
        txtBill.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        txtBill.setRows(5);
        jScrollPane2.setViewportView(txtBill);

        jLabel1.setText("Sale Summary");

        saleshomebttn.setText("Home");
        saleshomebttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saleshomebttnActionPerformed(evt);
            }
        });

        checkoutBtn.setText("Checkout");
        checkoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkoutBtnActionPerformed(evt);
            }
        });

        salesList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Line #", "ProdID", "Product Name", "Quantity", "Price", "Sub Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(salesList);

        jLabel2.setText("Sale List for Checkout");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(saleshomebttn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(checkoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane3))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(saleshomebttn)
                            .addComponent(checkoutBtn)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    //Balance calculated for Sales Summary bill to be displayed/printed in Sales Screen
    public void Balance()
    {
        double total = Double.valueOf(txtTotal.getText());
        double pay = Double.valueOf(txtPay.getText());
        double balance = pay-total;
        txtBalance.setText(String.format("%.2f",balance));
    }
    
    public void bill()
    {
        //Displays bill in Sales Screen
        String total = txtTotal.getText();
        String pay = txtPay.getText();
        String bal = txtBalance.getText();
        String payment = (String) paymentcombo.getSelectedItem();
        
        String date = new SimpleDateFormat("dd-MM-yyyy").format(new Date());
        
        DefaultTableModel model = new DefaultTableModel();
        
        model = (DefaultTableModel)salesList.getModel();
        
        txtBill.setText(txtBill.getText() + "*********************************************\n");
        txtBill.setText(txtBill.getText() + "*            POS BILL                        *\n");
        txtBill.setText(txtBill.getText() + "*********************************************\n");
        
        //Heading
        txtBill.setText(txtBill.getText() + "Date:" + "\t" + date + "\n");
        txtBill.setText(txtBill.getText() + "Product" + "\t\t\t" + "Quantity"+"\t"+"Price" + "\t"+ "Sub Total" + "\n" );
        
        for (int i = 0; i < model.getRowCount(); i++)
        {
            //Assigns each column of each line of the table in the Sales List for Checkout in the Sales Screen
            
            String pname = (String)model.getValueAt(i, 2);
            String quantity = Integer.toString((Integer)model.getValueAt(i, 3));
            String price = Double.toString((Double)model.getValueAt(i, 4));
            String subTotal = Double.toString((Double)model.getValueAt(i, 5));
            
            txtBill.setText(txtBill.getText() + pname + "\t" +quantity+"\t"+ price + "\t"+ subTotal + "\n" );
        }
        
        txtBill.setText(txtBill.getText() + "\n");
        txtBill.setText(txtBill.getText() + "\n");

        txtBill.setText(txtBill.getText() + "Total:" + "\t" + total + "\n");
        txtBill.setText(txtBill.getText() + "Pay:" + "\t" + pay + "\n");
        txtBill.setText(txtBill.getText() + "Balance: "  + bal + "\n");
        txtBill.setText(txtBill.getText() + "\t" + "\t" + "Payment\n\t\tType: "+ payment +"\t");
        txtBill.setText(txtBill.getText() + "\n");
        txtBill.setText(txtBill.getText() + "*********************************************\n");
        txtBill.setText(txtBill.getText() + "*            THANKYOU!!                     *\n");
        txtBill.setText(txtBill.getText() + "*            COME AGAIN!!                     *\n");
        txtBill.setText(txtBill.getText() + "*********************************************\n");

    }
    
    private void txtPcodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPcodeKeyPressed

    }//GEN-LAST:event_txtPcodeKeyPressed

    private void printBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printBillActionPerformed
        // TODO add your handling code here:
        Balance();
        bill();
        
    }//GEN-LAST:event_printBillActionPerformed

    private void saleshomebttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saleshomebttnActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Welcome obj4 = new Welcome();
        obj4.setVisible(true);
        
    }//GEN-LAST:event_saleshomebttnActionPerformed

    private void paymentcomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentcomboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paymentcomboActionPerformed

    private void txtPcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPcodeActionPerformed
    //Sets found product info to textboxes once focus is lost
    private void txtPcodeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPcodeFocusLost
        // TODO add your handling code here:
        txtPname.setText(getProdName());
        txtPrice.setText(Double.toString(getPrice()));
        txtSubtotal.setText(Double.toString(getSubtotal()));
    }//GEN-LAST:event_txtPcodeFocusLost

    private void quantityStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_quantityStateChanged
        // TODO add your handling code here:
        txtSubtotal.setText(Double.toString(getSubtotal()));
    }//GEN-LAST:event_quantityStateChanged

    private void checkoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkoutBtnActionPerformed
        // TODO add your handling code here:
        
        try
        {
            int salesCount = salesList.getRowCount();
            //Creates new data access object to insert sales record
            POSDAO checkoutDAO = new POSDAO();
            if(checkoutDAO.openConnection())
            {
                //Calls on insertSalesSummary in the POSDAO class, inserts lines into sales summary table, 
                //0 is placeholder for Invoice Num which the database will generate, "" also placeholder
                POS salesummary = new POS(0,"",QtySold,TotRevenue);
                txtTotal.setText(String.format("%.2f",TotRevenue));
                //insert products for checkout into sales summary table
                checkoutDAO.insertSalesSummary(salesummary);
                InvoiceNum = checkoutDAO.SaleSummary().getInvoiceNum();
                
                for(int row=0; row<salesCount; row++)
                {
                    //for each row of the sales list in the Sales Screen, create a sales record
                    POS salerecord = new POS(InvoiceNum,(Integer)salesList.getValueAt(row, 0), (Integer)salesList.getValueAt(row,1), (Integer)salesList.getValueAt(row, 3), (Double)salesList.getValueAt(row, 5));
                    //Calls on insertSalesRecord in the POSDAO class, inserts lines into sales DETAILS table, 
                    checkoutDAO.insertSalesRecord(salerecord);
                }
                
            }
            //clearSalesTable();
        } catch (SQLException ex) {
            Logger.getLogger(POS.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_checkoutBtnActionPerformed
    //clears the table on call
    public void clearSalesTable(){
        DefaultTableModel model = (DefaultTableModel)salesList.getModel();
        model.addRow(new Object[]
        {
            "",
            "",
            "",
            "",
            "",
            "",
            "",
        });
    }
    //adds line of new sale into sales list for checkout
    private void addLineBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addLineBtnActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)salesList.getModel();
        lineCounter++;
        TotRevenue = TotRevenue + Double.valueOf(txtSubtotal.getText());
        txtTotal.setText(String.format("%.2f",TotRevenue));
        QtySold = QtySold + (Integer)quantity.getValue();
        model.addRow(new Object[]
        {
            lineCounter,
            Integer.valueOf(txtPcode.getText()),
            txtPname.getText(),
            (Integer)quantity.getValue(),
            Double.valueOf(txtPrice.getText()),
            Double.valueOf(txtSubtotal.getText()),
        });
    }//GEN-LAST:event_addLineBtnActionPerformed

    private void txtPayFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPayFocusLost
        // TODO add your handling code here:
        Balance();
    }//GEN-LAST:event_txtPayFocusLost

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(POS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(POS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(POS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(POS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new POS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addLineBtn;
    private javax.swing.JButton checkoutBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblBalance;
    private javax.swing.JLabel lblPay;
    private javax.swing.JLabel lblPcode;
    private javax.swing.JLabel lblPname;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblQty;
    private javax.swing.JLabel lblSubtotal;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JComboBox<String> paymentcombo;
    private javax.swing.JButton printBill;
    private javax.swing.JSpinner quantity;
    private javax.swing.JTable salesList;
    private javax.swing.JButton saleshomebttn;
    private javax.swing.JTextField txtBalance;
    private javax.swing.JTextArea txtBill;
    private javax.swing.JTextField txtPay;
    private javax.swing.JTextField txtPcode;
    private javax.swing.JTextField txtPname;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtSubtotal;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables

    
}
