/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Sales;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kp
 */
public class Products extends javax.swing.JFrame {

    /**
     * Creates new form Productss
     */
    public Products() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtpid = new javax.swing.JTextField();
        lblPid = new javax.swing.JLabel();
        lblpname = new javax.swing.JLabel();
        txtpname = new javax.swing.JTextField();
        lblUnitprice = new javax.swing.JLabel();
        txtunitprice = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        P_Cancel = new javax.swing.JButton();
        txtonhand = new javax.swing.JTextField();
        lblonhand = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        P_update = new javax.swing.JButton();
        P_delete = new javax.swing.JButton();
        P_exit = new javax.swing.JButton();
        homebttn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Products", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        txtpid.setBackground(new java.awt.Color(0, 0, 0));
        txtpid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtpid.setForeground(new java.awt.Color(255, 255, 0));
        txtpid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpidActionPerformed(evt);
            }
        });
        txtpid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpidKeyPressed(evt);
            }
        });

        lblPid.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblPid.setForeground(new java.awt.Color(255, 255, 255));
        lblPid.setText("Product ID");

        lblpname.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblpname.setForeground(new java.awt.Color(255, 255, 255));
        lblpname.setText("Product Name");

        txtpname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        lblUnitprice.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblUnitprice.setForeground(new java.awt.Color(255, 255, 255));
        lblUnitprice.setText("Unit Price");

        txtunitprice.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        addButton.setFont(new java.awt.Font("Calibri Light", 0, 22)); // NOI18N
        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        P_Cancel.setFont(new java.awt.Font("Calibri Light", 0, 22)); // NOI18N
        P_Cancel.setText("Cancel");
        P_Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P_CancelActionPerformed(evt);
            }
        });

        txtonhand.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        lblonhand.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblonhand.setForeground(new java.awt.Color(255, 255, 255));
        lblonhand.setText("Onhand");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(P_Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblPid, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                            .addComponent(txtpid))
                        .addGap(67, 67, 67)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblpname)
                            .addComponent(txtpname, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtunitprice, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblUnitprice))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblonhand)
                            .addComponent(txtonhand, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 137, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPid)
                    .addComponent(lblpname)
                    .addComponent(lblUnitprice)
                    .addComponent(lblonhand))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtpid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtpname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtunitprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtonhand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(P_Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ProductID", "ProductName", "Unit Price", "Onhand"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setShowGrid(true);
        jScrollPane1.setViewportView(jTable1);

        jPanel2.setBackground(new java.awt.Color(255, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        P_update.setFont(new java.awt.Font("Calibri Light", 0, 22)); // NOI18N
        P_update.setText("Update");
        P_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P_updateActionPerformed(evt);
            }
        });

        P_delete.setFont(new java.awt.Font("Calibri Light", 0, 22)); // NOI18N
        P_delete.setText("Delete");
        P_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P_deleteActionPerformed(evt);
            }
        });

        P_exit.setFont(new java.awt.Font("Calibri Light", 0, 22)); // NOI18N
        P_exit.setText("Exit");
        P_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P_exitActionPerformed(evt);
            }
        });

        homebttn.setText("Home");
        homebttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homebttnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(P_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(P_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(P_update, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(homebttn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(P_update, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addComponent(P_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83)
                .addComponent(P_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(homebttn)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtpidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpidKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            String pcode = txtpid.getText();

            try {
                Class.forName("com.mysql.jdbc.Driver");
                //              con = DriverManager.getConnection("jdbc:mysql://localhost/tahirautos","root","");

            } catch (ClassNotFoundException ex) {
                //       Logger.getLogger(pos.class.getName()).log(Level.SEVERE, null, ex);
            }

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_txtpidKeyPressed

    private void txtpidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpidActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = new DefaultTableModel();
        
        model = (DefaultTableModel)jTable1.getModel();
        
        model.addRow(new Object[]
                
        {
            txtpid.getText(),
            txtpname.getText(),
            txtunitprice.getText(),
            txtonhand.getText(),
      
        });
        
        
        
        
        if(txtpid.getText().isEmpty()){

            JOptionPane.showMessageDialog(null, "Please Enter Product ID!","Error!!", ERROR_MESSAGE);

        }

        else if(txtpname.getText().isEmpty()){

            JOptionPane.showMessageDialog(null, "Please Enter Product Name!","Error!!", ERROR_MESSAGE);

        }

        else {
            try{
                String sql = "INSERT INTO (tablename)"
                +"(ID, Name)"
                +"VALUES (?,?)";
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost/(database)","root","");
                PreparedStatement pst = con.prepareStatement(sql);
                pst.setString(1,txtpid.getText());
                pst.setString(2,txtpname.getText());
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "Added");
                txtpid.setText(""+autoOderId());
                con.close();
            }

            catch(SQLException | HeadlessException ex){
                JOptionPane.showMessageDialog(null, ex);
            }

            txtpname.setText("");
            //showTableData();
        }
    }//GEN-LAST:event_addButtonActionPerformed

    private void P_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P_updateActionPerformed
        // TODO add your handling code here:
        if(txtpid.getText().isEmpty()){

            JOptionPane.showMessageDialog(null, "Please Enter Product ID!","Error!!", ERROR_MESSAGE);

        }

        else if(txtpname.getText().isEmpty()){

            JOptionPane.showMessageDialog(null, "Please Enter Product Name!","Error!!", ERROR_MESSAGE);

        }

        else{
            try{
                String sql = "UPDATE (tablename) SET  Name=? WHERE ID=?";
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost/(databasename)","root","");
                PreparedStatement pst = con.prepareStatement(sql);
                pst.setString(2,txtpid.getText());
                pst.setString(1,txtpname.getText());
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "Updated");
                txtpid.setText(""+autoOderId());
                con.close();
            }
            catch(SQLException | HeadlessException ex){
                JOptionPane.showMessageDialog(null, ex);
            }

            txtpname.setText("");
            //showTableData();

        }
    }//GEN-LAST:event_P_updateActionPerformed

    private void P_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P_deleteActionPerformed
        // TODO add your handling code here:

        try{
            String sql = "DELETE FROM (table) WHERE ID =?";
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/(database)","root","");
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1,txtpid.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Deleted ");
            txtpid.setText(""+autoOderId());
            con.close();
        }
        catch(SQLException | HeadlessException ex){
            JOptionPane.showMessageDialog(null, ex);
        }
        txtpname.setText("");
        //showTableData();
    }//GEN-LAST:event_P_deleteActionPerformed

    private void P_CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P_CancelActionPerformed
        // TODO add your handling code here:
        txtpname.setText("");
        showTableData();
    }//GEN-LAST:event_P_CancelActionPerformed

    private void P_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P_exitActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_P_exitActionPerformed

    private void homebttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homebttnActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Welcome obj3 = new Welcome();
        obj3.setVisible(true);
        
    }//GEN-LAST:event_homebttnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Products().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton P_Cancel;
    private javax.swing.JButton P_delete;
    private javax.swing.JButton P_exit;
    private javax.swing.JButton P_update;
    private javax.swing.JButton addButton;
    private javax.swing.JButton homebttn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblPid;
    private javax.swing.JLabel lblUnitprice;
    private javax.swing.JLabel lblonhand;
    private javax.swing.JLabel lblpname;
    private javax.swing.JTextField txtonhand;
    private javax.swing.JTextField txtpid;
    private javax.swing.JTextField txtpname;
    private javax.swing.JTextField txtunitprice;
    // End of variables declaration//GEN-END:variables

    private String autoOderId() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
